---
- name: "Include variable configuration tasks."
  ansible.builtin.import_tasks: "set_vars.yml"

- name: "Include setup tasks."
  ansible.builtin.import_tasks: "setup.yml"

- name: "Include configuration tasks."
  ansible.builtin.import_tasks: "configure.yml"

- name: "Include systemd tasks."
  ansible.builtin.import_tasks: "systemd.yml"

- name: "Flush handlers."
  ansible.builtin.meta: "flush_handlers"
